### ISSUE TITLE
Use of domain * results in a tricky filename

### ISSUE THREAD

**Issue by miketheman** [bmhatfield/chef-ulimit#20]
Not a hard bug per se, but if I wanted to set limits on all users for a given system, I'd typically use * domain.

```ruby
ulimit_domain '*' do
  rule do
    item :nofile
    type :hard
    value 10000
  end
  rule do
    item :nofile
    type :soft
    value 5000
  end
end
```

Creates the file that I think I want, but it creates: `/etc/security/limits.d/\*.conf` - not the best filename I've seen this week.

I think the issue is that the domain_name attribute for the ulimit_domain is largely unseen, so that this would work just fine:

```ruby
ulimit_domain 'systemwide' do
  domain_name '*'
...
end
```

So really a documentation bug. :wink:

**Comment by bmhatfield** [comment]
Fixed in #35
