### ISSUE TITLE
Not working with Ubuntu

### ISSUE THREAD

**Issue by allaire** [bmhatfield/chef-ulimit#29]
I tried everything, Chef run runs successfully, files are in `/etc/security/limits.d`

I include the recipe `ulimit` to overwrite the pam file under Ubuntu, rebooted, etc. I tried everything and `ulimit -n` is always returns `1024`!

Here's my snippet

``` ruby
include_recipe 'ulimit'

# Boost up ulimit

user_ulimit "root" do
  filehandle_soft_limit 10000
  filehandle_hard_limit 30000
end

ulimit_domain 'wildcard' do
  domain_name '*'

  rule do
    item :nofile
    type :soft
    value 10000
  end

  rule do
    item :nofile
    type :hard
    value 30000
  end
end
```

Any ideas?

**Comment by alez007** [comment]
I don't think you figured it out, I don't see it working at all on 14.04. Files are created, while 
`su - www-data -c 'ulimit -aHS' -s '/bin/bash'`
returns 1024
