### ISSUE TITLE
new tag?

### ISSUE THREAD

**Issue by mreeves1** [bmhatfield/chef-ulimit#37]
It's been a while (October 2013) since you have made a release/tag. Now that chef-dk and berkshelf are the standard chef cookbook managment tools this sha: https://github.com/bmhatfield/chef-ulimit/commit/936d3c8ecba638de9a91a934de46347d31fcfdde fixes your cookbook from breaking in berkshelf per this issue: https://github.com/berkshelf/berkshelf/issues/1019. 

Thanks for all your contributions and apologies if this is not appropriate as an "issue".

**Comment by bmhatfield** [comment]
On it's way!

**Comment by bmhatfield** [comment]
https://github.com/bmhatfield/chef-ulimit/tree/v0.3.3 published, and updated on Supermarket.

**Comment by mreeves1** [comment]
Awesome! Thanks!
