### ISSUE TITLE
Can you modify open files? 

### ISSUE THREAD

**Issue by spuder** [bmhatfield/chef-ulimit#38]
Can you modify the max number of open files with this cookbook? 

The default is 1024

    ulimit -n 2048

**Comment by bmhatfield** [comment]
Yes!

Check out https://github.com/bmhatfield/chef-ulimit#usage

Good luck!

**Comment by bmhatfield** [comment]
Resolved in the #chef IRC room.

**Comment by spuder** [comment]
I've tried the following

```

user_ulimit 'kafka' do
  rule do
    item :nofile
    type :hard
    value 10000
  end
  rule do
    item :nofile
    type :soft
    value 5000
  end
end

```

While it did create a file at /etc/security/limits.d/kafka_limits.conf, it is pretty much a blank file. 

```
# Limits settings for kafka













~
~
~
~
~
```


https://gist.github.com/bmhatfield/99c8a1f4a71231d8449b

However I don't acutally need to use this cookbook, as pointed out in the IRC chanel, the kafka cookbook has build in support for modifying the ulimit

https://github.com/mthssdrbrg/kafka-cookbook/blob/master/templates/default/upstart/default.erb#L10-L12

**Comment by bmhatfield** [comment]
Hi,
You used the `ulimit_domain` syntax in the `user_ulimit` resource, which is why it isn't working :-)
